return {
	-- "olimorris/codecompanion.nvim",
	-- lazy = true,
	-- event = { "BufReadPre", "VeryLazy" },
	-- dependencies = {
	-- 	"nvim-lua/plenary.nvim",
	-- 	"nvim-treesitter/nvim-treesitter",
	-- 	"hrsh7th/nvim-cmp", -- Optional: For using slash commands and variables in the chat buffer
	-- 	{
	-- 		"stevearc/dressing.nvim", -- Optional: Improves the default Neovim UI
	-- 		opts = {
	-- 			adapters = {
	-- 				openai = function()
	-- 					return require("codecompanion.adapters").extend("openai", {
	-- 						env = {
	-- 							api_key = "cmd:bws secret get f3a6ad3d-2382-45f2-9dc6-b1e7001e769c | jq -r .value",
	-- 						},
	-- 						schema = {
	-- 							model = {
	-- 								-- Use the advanced but cheap guy.
	-- 								default = "gpt-4o-mini",
	-- 							},
	-- 						},
	-- 					})
	-- 				end,
	-- 			},
	-- 		},
	-- 	},
	-- },
	-- config = true,
}
